export enum TransactionType {
	DEPOSIT = "DEPOSIT",
	WITHDRAW = "WITHDRAW",
	PURCHASE = "PURCHASE",
	REFUND = "REFUND",
	TRANSFER = "TRANSFER",
	PURCHASEDRECIPE = "PURCHASEDRECIPE",
	BOOKING = "BOOKING",
}
